#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# frontend
cd frontend

echo "\n 🚧🏗️  Next.js: Checking format, lint in your project before committing$"

# Check Prettier standards
npm run check-format ||
(
    echo "\n ❌🟨 Prettier Check Failed$. 🟨❌\n Run npm run format$, add changes and try commit again.\n";
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo "\n ❌🟪 ESLint Check Failed$. 🟪❌\n Make the required changes listed above, add changes and try to commit again.\n"
    false;
)

echo "✅✅ All completed!!"

# backend