#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# frontend
cd frontend

echo "\n 🚧🏗️  Next.js: Checking format, lint, stylelint in your project before committing"

# Check Prettier ESLint stylelint standards
npm run lint-fix ||
(
    echo "\n ❌🟨 Check Failed$";
    false;
)


# backend
cd ../
cd backend

flake8