#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# frontend
cd frontend

echo "\n 🚧🏗️  frontend: Checking format, lint, stylelint in your project before committing"

# Check Prettier ESLint stylelint standards
npm run lint-fix ||
(
    echo "\n ❌🟨 Check Failed$";
    false;
)


# backend
cd ../
cd backend

echo "\n 🚧🏗️  backend: Checking format, lint, stylelint in your project before committing"

flake8 # リンター
black app # コードフォーマッター
mypy app # 型チェック